In [2]:
import numpy as np

In [23]:
xv = np.array([[1,2,3],[2,2,3]])
yv = np.array([[1,2,3],[2,2,3]])



In [24]:
KE = (np.power(xv,2) + np.power(yv,2))/2


In [25]:
KE

array([[1., 4., 9.],
       [4., 4., 9.]])

In [3]:
ar = np.array([1,2,3,5])

In [13]:
np.where(ar % 2)

(array([0, 2, 3]),)

In [20]:
t = ar[np.where(ar % 2)] -1

In [21]:
for i in t:
    print(i)

0
2
4


In [13]:
np.sum(np.power(ar,2), axis=1)

array([39, 30])

In [4]:
pos=[[-1.74407353e-02,-4.11951123e-01,-3.98252730e-01,-3.25972266e-01
,-3.51085048e-01,-3.46339180e-01,-1.82355517e-01,-5.15291263e-01
,-6.25068901e-02,-2.46036183e-01,-1.19796448e-03,3.98150967e-01
,-2.65563398e-01,-2.98835857e-01,1.64465745e-01,2.95220880e-01
,-1.69345656e-01,-3.92106281e-01,8.37930837e-01,4.51588536e-03
,7.13856863e-01,2.01342585e-01,-1.62955072e-01,7.49901338e-01
,3.23009030e-02,-8.12188060e-01,9.34787048e-02,-5.03435322e-01
,-5.98376899e-01,-2.11287103e-01,1.60681758e-04,-5.42209833e-01
,-2.54821624e-01,-5.00633470e-01,-1.20114462e-01,5.03895607e-01
,6.57763419e-02,1.94605397e-01,-2.78428024e-01,-2.12330522e-01
,-3.38293631e-01,5.28365722e-01,3.17477575e-02,-7.90484289e-02
,5.50781956e-01,1.21062332e-01,6.58211666e-01,1.02392507e-01
,4.72785787e-01,2.32335757e-01,-1.34672250e-02,1.82310664e-01
,-8.37163945e-01,-5.60302389e-01,-6.63332498e-02,2.32280211e-01
,-3.69686574e-01,-4.95981197e-01,-4.94189885e-01,-1.86855777e-01
,-9.14074978e-02,5.14059731e-01,3.49000099e-01,-3.07461878e-02
,1.21724064e-02,7.38522838e-01,3.55441416e-01,4.53927958e-01
,2.07495512e-01,-3.89371832e-02,-1.64741850e-01,-1.74181656e-01
,8.58163100e-01,5.57855909e-01,2.18833438e-01,-7.49454982e-01
,-7.24821808e-02,-8.50955164e-01,1.49807480e-01,-7.89521898e-01
,-6.80045007e-02,9.48133170e-02,-7.95639957e-01,-2.55993622e-01
,2.72203287e-01,1.30973255e-01,-3.49693584e-01,-1.24776890e-01
,-3.71366261e-01,5.15688311e-02,-4.21089575e-01,2.18559188e-01
,9.87901178e-02,-3.27534606e-01,3.66003358e-01,6.84757279e-01
,-1.05172853e-01,9.16425026e-01,3.07662469e-01,2.20202637e-01
,-8.10694454e-01,-6.27351670e-01,-3.51645199e-01,2.33832191e-01
,-3.11298159e-01,-1.20239284e-01,-4.74135630e-01,-1.99368293e-01
,-5.62277723e-01,-6.70702398e-01,-2.15139377e-01,2.30442687e-01
,2.17416671e-01,-4.14146646e-01,-1.67809542e-01,6.69919115e-01
,3.00791938e-01,8.11973464e-02,1.98324011e-02,2.00050262e-02
,4.12092327e-01,7.06305411e-01,5.03753944e-01,4.08258662e-01
,7.32397158e-01]
,[-7.37985379e-01,-3.02705078e-01,-6.73951271e-01,-4.18547108e-01
,-2.56296959e-01,-7.94920509e-01,-6.16411528e-01,-6.93650401e-01
,2.40882686e-01,-2.17360411e-01,-3.83663065e-01,-8.75327507e-01
,-6.45429341e-01,-5.46462233e-01,-2.28628299e-01,-4.22168523e-01
,-1.25898229e-01,-7.08911523e-01,-2.94410228e-01,2.10962172e-01
,-3.81421266e-01,-2.63480097e-01,-4.70541435e-01,-2.46715321e-01
,1.80124637e-01,2.13748233e-01,-6.71000802e-01,-8.20467260e-01
,4.55168527e-01,-8.96828902e-02,-1.66442139e-01,6.57248492e-02
,-2.93919817e-01,-6.67323609e-01,-1.97565958e-01,2.79947907e-01
,-3.83438429e-01,5.58464644e-01,2.85287931e-01,3.40320418e-01
,-1.84910795e-01,6.49332939e-02,1.01254349e-01,3.61202139e-01
,-2.85711448e-01,-7.12108289e-01,4.36385584e-01,-8.09756408e-01
,-2.58752298e-01,1.26569523e-01,-3.87760655e-01,4.04645363e-02
,4.11599009e-01,6.75725680e-01,2.81100457e-01,1.45408365e-01
,2.98089602e-01,-5.15886348e-01,-2.63111460e-01,1.57447308e-01
,3.91215688e-01,-2.08105917e-01,1.04047307e-01,4.13490569e-01
,1.78175290e-02,3.39133138e-01,8.12443161e-02,-3.32536666e-02
,-4.03463919e-01,-2.59750532e-01,-2.98359707e-01,2.50178598e-01
,-4.69702156e-01,3.55128699e-02,1.15176757e-01,8.27163610e-02
,7.08206884e-01,1.38873978e-01,-1.77831969e-01,1.99448013e-01
,2.96335381e-01,-1.30496393e-01,5.34355140e-01,2.18814385e-01
,-2.75433687e-01,7.41881355e-01,-3.77600496e-01,6.57410553e-01
,7.84556235e-01,1.45579194e-01,2.54008113e-01,-3.93740499e-01
,3.31669575e-01,-2.53750311e-01,6.31262659e-01,-3.62189552e-01
,5.27397792e-02,-2.57350305e-01,-1.01434515e-02,1.19272337e-01
,-1.09728365e-01,5.81321293e-01,3.92355354e-01,4.23111061e-01
,1.67202299e-01,-2.84151710e-01,5.92952036e-01,2.05576515e-01
,2.73638887e-01,1.64436758e-01,4.47809132e-01,2.39516243e-01
,8.89035497e-01,6.77531441e-01,5.65886875e-01,-9.89134168e-02
,2.45837111e-01,8.95637503e-01,7.03148145e-01,4.79097420e-01
,-8.06984683e-03,5.77473924e-01,5.45271757e-01,-7.23826539e-02
,-1.55524711e-03]
,[-4.56168782e-01,-8.17711259e-01,4.65751412e-01,7.24465355e-01
,-2.79110375e-01,-1.45155660e-01,4.61155197e-01,-2.50018086e-01
,4.33896232e-01,7.63384066e-01,2.95696876e-01,1.16132804e-01
,5.94680464e-01,7.54163449e-01,8.46756978e-01,-5.01272391e-01
,3.22271203e-01,1.95655790e-01,-5.73668991e-02,6.69861998e-01
,-9.53691521e-02,4.52471832e-01,-4.03170720e-01,1.89099025e-01
,5.11614097e-01,-2.15386563e-02,-6.24163622e-02,1.73891201e-01
,7.46116825e-02,8.49682766e-01,-9.07567642e-01,3.43939654e-01
,6.87261529e-01,-2.19203013e-01,8.41173249e-01,-3.86355360e-01
,-8.68164477e-01,-1.63979237e-01,6.13927122e-01,7.83692813e-01
,4.05703266e-02,3.53451806e-01,3.82201133e-01,5.02547463e-01
,-1.94890136e-01,-6.27323220e-01,-3.12602556e-01,1.55672355e-01
,7.60992623e-01,9.36239087e-01,-8.29589675e-01,-5.78570044e-01
,-3.50974221e-01,1.55063129e-01,9.42016322e-01,1.25445073e-01
,-8.05723833e-01,3.61855587e-01,-3.73425797e-01,8.65232791e-01
,1.68277357e-01,-6.21350312e-01,-5.92901179e-01,-3.59044737e-01
,9.06310056e-01,-1.18134233e-01,-8.73700364e-01,6.47086845e-01
,-3.67010514e-01,9.42185353e-01,-6.76456387e-01,-5.02491183e-01
,-1.31896051e-01,-4.76836874e-01,-2.63455059e-01,-3.00568405e-01
,1.44530798e-01,-4.61834005e-01,1.94870395e-03,2.13446442e-01
,-8.17681769e-01,-7.37016320e-01,-1.33375172e-01,-4.93481139e-01
,2.12210775e-01,-5.62085749e-01,-3.08629197e-02,5.09306390e-01
,2.69360470e-01,-2.91766930e-01,-9.09900007e-02,-5.61425670e-01
,6.75839347e-01,2.13532028e-01,4.97304947e-01,-1.04725380e-01
,-6.55458944e-01,-9.24913892e-02,-4.57063211e-01,-2.66482246e-01
,-5.45314263e-01,2.08440290e-01,6.94160146e-01,-8.63137856e-02
,6.78535421e-01,-3.02050210e-01,4.09940650e-01,-6.68225455e-01
,7.80362429e-01,6.12779944e-01,-6.11604088e-01,-8.36693849e-01
,-2.46862096e-01,5.20422267e-01,-2.54564373e-01,-5.20679506e-01
,4.71087123e-01,-3.04166602e-01,5.51148659e-01,-2.67498527e-01
,-8.37252182e-01,3.60667211e-01,1.01173554e-01,-3.10810211e-01
,5.02509370e-01]]

In [5]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


In [ ]:
pos[:,0]

In [8]:
fig = plt.figure()#figsize=plt.figaspect(2.))
ax = fig.add_subplot(projection='3d')
ax.scatter(pos[0], pos[1], pos[2])